"""The identity of a build: package version and commit, DuckDB version and commit.

Also the scikit-build-core metadata provider for the package version, see
``[tool.scikit-build] metadata.version.provider`` in pyproject.toml.

Two independent overrides force the two halves. OVERRIDE_GIT_DESCRIBE forces the
package version, and DuckDB inherits it minus any post suffix, because a stable
release uses one version identifier for both. OVERRIDE_DUCKDB_GIT_DESCRIBE forces
the version DuckDB is built with and nothing else, which is what a nightly that
vendors a specific DuckDB version needs: it keeps deriving its own version.

Without overrides a git checkout yields a dev build: the release version declared
in pyproject.toml plus a dev segment made of the latest commit time across this
repository and the submodule. An sdist carries the identity it was built with in
build_info.json, because it has no git history to derive it from.
"""

import dataclasses
import functools
import json
import os
import re
import subprocess
import sys
from pathlib import Path

from ._versioning import (
    PROJECT_ROOT,
    commit_hash,
    commit_time,
    dev_number,
    duckdb_describe_from_override,
    duckdb_dev_version,
    git_tag_to_pep440,
    release_version,
)

OVERRIDE_GIT_DESCRIBE_ENV_VAR = "OVERRIDE_GIT_DESCRIBE"
OVERRIDE_DUCKDB_GIT_DESCRIBE_ENV_VAR = "OVERRIDE_DUCKDB_GIT_DESCRIBE"

BUILD_INFO_JSON = Path(__file__).with_name("build_info.json")
BUILD_INFO_MODULE = PROJECT_ROOT / "duckdb" / "_build_info.py"

# A forced package version is an exact release: vX.Y.Z with an optional -postN or
# pre-release suffix. A describe distance (-N-g<hash>) has no meaning for a release.
_FORCED_VERSION_RE = re.compile(r"^v\d+\.\d+\.\d+(?:-post\d+|-(?:alpha|beta|preview|pre|rc|a|b|c)\d+)?$")

_MODULE_TEMPLATE = '''"""Generated by duckdb_packaging at build time. Do not edit, do not commit."""

PACKAGE_COMMIT = {package_commit!r}
'''


@dataclasses.dataclass(frozen=True)
class BuildInfo:
    """What a build is made from. The two commits identify it, the two versions label it."""

    package_version: str
    package_commit: str
    duckdb_version: str
    duckdb_commit: str


def is_git_checkout() -> bool:
    """Whether the project root is a git checkout (a worktree's .git is a file, hence exists)."""
    return (PROJECT_ROOT / ".git").exists()


def in_sdist() -> bool:
    """Whether the project root is an unpacked sdist: it has the stored identity and PKG-INFO."""
    return BUILD_INFO_JSON.exists() and (PROJECT_ROOT / "PKG-INFO").exists()


def forced_version_from_env() -> str | None:
    """The package version forced through OVERRIDE_GIT_DESCRIBE, in canonical PEP440 form.

    Returns:
        The version, or None when the variable is unset or empty

    Raises:
        ValueError: If the value is not an exact release version
    """
    value = os.getenv(OVERRIDE_GIT_DESCRIBE_ENV_VAR)
    if not value:
        return None
    if not _FORCED_VERSION_RE.match(value):
        msg = (
            f"Invalid {OVERRIDE_GIT_DESCRIBE_ENV_VAR}: {value!r} "
            "(expected vX.Y.Z with an optional -postN or pre-release suffix)"
        )
        raise ValueError(msg)
    return git_tag_to_pep440(value)


def forced_duckdb_version_from_env() -> str | None:
    """The version DuckDB was explicitly asked to build as, if any.

    OVERRIDE_DUCKDB_GIT_DESCRIBE wins and is passed on verbatim. Otherwise a
    forced package version carries over, minus its post suffix. Returns None when
    neither is set, and the caller derives the version from the submodule instead.

    Returns:
        The version string to build DuckDB with, or None to derive it.
    """
    forced_duckdb = os.getenv(OVERRIDE_DUCKDB_GIT_DESCRIBE_ENV_VAR)
    if forced_duckdb:
        print(f"[versioning] Found {OVERRIDE_DUCKDB_GIT_DESCRIBE_ENV_VAR}={forced_duckdb}")
        return forced_duckdb

    forced_package = os.getenv(OVERRIDE_GIT_DESCRIBE_ENV_VAR)
    if forced_package:
        duckdb_version = duckdb_describe_from_override(forced_package)
        print(f"[versioning] Derived DuckDB version {duckdb_version} from {OVERRIDE_GIT_DESCRIBE_ENV_VAR}")
        return duckdb_version

    return None


def duckdb_submodule_path() -> Path:
    """Verify that the duckdb submodule is checked out and usable and return its path."""
    if not is_git_checkout():
        msg = "Not in a git repository, no duckdb submodule present"
        raise RuntimeError(msg)
    modules = {}
    try:
        gitmodules = (PROJECT_ROOT / ".gitmodules").open("r")
    except FileNotFoundError:
        msg = f"DuckDB submodule missing: no .gitmodules in {PROJECT_ROOT}"
        raise RuntimeError(msg) from None
    with gitmodules as f:
        cur_module_path = None
        cur_module_reponame = None
        for line in f:
            if line.strip().startswith("[submodule"):
                if cur_module_reponame is not None and cur_module_path is not None:
                    modules[cur_module_reponame] = cur_module_path
                    cur_module_reponame = None
                    cur_module_path = None
            elif line.strip().startswith("path"):
                cur_module_path = line.split("=")[-1].strip()
            elif line.strip().startswith("url"):
                basename = Path(line.split("=")[-1].strip()).name
                cur_module_reponame = basename[:-4] if basename.endswith(".git") else basename
        if cur_module_reponame is not None and cur_module_path is not None:
            modules[cur_module_reponame] = cur_module_path

    if "duckdb" not in modules:
        msg = "DuckDB submodule missing"
        raise RuntimeError(msg)

    duckdb_path = modules["duckdb"]
    status = subprocess.run(
        ["git", "submodule", "status", duckdb_path],
        capture_output=True,
        text=True,
        check=False,
        cwd=PROJECT_ROOT,
    ).stdout
    for line in status.splitlines():
        if line.startswith("-"):
            msg = f"Duckdb submodule not initialized: {line}"
            raise RuntimeError(msg)
        if line.startswith("U"):
            msg = f"Duckdb submodule has merge conflicts: {line}"
            raise RuntimeError(msg)
        if line.startswith("+"):
            print(f"[versioning] WARNING: Duckdb submodule not clean: {line}", file=sys.stderr)
    return PROJECT_ROOT / duckdb_path


@functools.cache
def resolve_build_info() -> BuildInfo:
    """Settle the identity of the build at hand.

    A forced package version must be the release version pyproject.toml declares,
    so a release can never be cut from a branch that was not bumped for it. An
    sdist compiles the very source it was cut from, so its identity was settled
    when it was built and an override can only restate it.

    Cached: the metadata hook and the build hooks ask within one process, and
    nothing the answer depends on changes in between.

    Returns:
        The build identity

    Raises:
        ValueError: If an override is malformed, contradicts pyproject.toml, or contradicts the sdist
        RuntimeError: If there is neither a git checkout nor an sdist to derive it from
    """
    stored = read_build_info() if in_sdist() else None
    declared = release_version()
    forced_package = forced_version_from_env()
    if forced_package is not None and forced_package != declared:
        msg = (
            f"{OVERRIDE_GIT_DESCRIBE_ENV_VAR} resolves to {forced_package}, but pyproject.toml declares "
            f"release_version = {declared}. Bump release_version first."
        )
        raise ValueError(msg)
    forced_duckdb = forced_duckdb_version_from_env()

    if stored is not None:
        if forced_package is not None and forced_package != stored.package_version:
            msg = (
                f"{OVERRIDE_GIT_DESCRIBE_ENV_VAR} resolves to {forced_package}, but this sdist was built as "
                f"{stored.package_version} at {stored.package_commit}"
            )
            raise ValueError(msg)
        if forced_duckdb is not None and forced_duckdb != stored.duckdb_version:
            msg = (
                f"DuckDB is forced to {forced_duckdb}, but this sdist was built with DuckDB "
                f"{stored.duckdb_version} at {stored.duckdb_commit}"
            )
            raise ValueError(msg)
        return stored
    if not is_git_checkout():
        msg = "Not in a git repository nor in an sdist, can't determine what is being built"
        raise RuntimeError(msg)
    submodule = duckdb_submodule_path()
    package_version = forced_package or f"{declared}.dev{dev_number(commit_time(PROJECT_ROOT), commit_time(submodule))}"
    return BuildInfo(
        package_version=package_version,
        package_commit=commit_hash(PROJECT_ROOT),
        duckdb_version=forced_duckdb or duckdb_dev_version(submodule),
        duckdb_commit=commit_hash(submodule),
    )


def read_build_info(path: Path | None = None) -> BuildInfo:
    """Read the identity an sdist was built with."""
    with (path or BUILD_INFO_JSON).open("r", encoding="utf-8") as f:
        return BuildInfo(**json.load(f))


def write_build_info_json(info: BuildInfo, path: Path | None = None) -> None:
    """Store the identity for the sdist to carry along."""
    with (path or BUILD_INFO_JSON).open("w", encoding="utf-8") as f:
        json.dump(dataclasses.asdict(info), f, indent=2)
        f.write("\n")


def write_build_info_module(info: BuildInfo, path: Path | None = None) -> None:
    """Generate the module that exposes the package commit at runtime."""
    (path or BUILD_INFO_MODULE).write_text(
        _MODULE_TEMPLATE.format(package_commit=info.package_commit), encoding="utf-8"
    )


def dynamic_metadata(field: str, settings: dict[str, object] | None = None) -> str:
    """scikit-build-core metadata provider hook: the package version."""
    if field != "version":
        msg = "Only the 'version' field is supported"
        raise ValueError(msg)
    if settings:
        msg = "No inline configuration is supported"
        raise ValueError(msg)
    return resolve_build_info().package_version


def get_requires_for_dynamic_metadata(_settings: dict[str, object] | None = None) -> list[str]:
    """scikit-build-core metadata provider hook: nothing beyond the build backend itself."""
    return []
