# ----------------------------------------------------------------------
# Version API
#
# We provide four symbols:
# - duckdb.__version__: The version of this package
# - duckdb.__duckdb_version__: The version of duckdb that is bundled
# - duckdb.version(): A human-readable version string containing both of the above
# - duckdb.build_info(): The versions and the commits this build was made from
# ----------------------------------------------------------------------
import importlib
from importlib.metadata import version as _dist_version

import _duckdb

__version__: str = _dist_version("duckdb")
"""Version of the DuckDB Python Package."""

__duckdb_version__: str = _duckdb.__version__
"""Version of DuckDB that is bundled."""


def version() -> str:
    """Human-friendly formatted version string of both the distribution package and the bundled DuckDB engine."""
    return f"{__version__} (with duckdb {_duckdb.__version__})"


def _package_commit() -> str:
    # The module is generated by the build backend, a bare source tree has none.
    try:
        return str(importlib.import_module("duckdb._build_info").PACKAGE_COMMIT)
    except (ImportError, AttributeError):
        return "unknown"


def build_info() -> dict[str, str]:
    """The versions and the commits this build was made from, for the package and the bundled DuckDB engine."""
    return {
        "package_version": __version__,
        "package_commit": _package_commit(),
        "duckdb_version": __duckdb_version__,
        "duckdb_commit": _duckdb.__git_revision__,
    }
